### ISSUE TITLE
有办法能够让不支持交互的命令行顺利启动服务嘛，就像之前可以配置好之后一键启动

### ISSUE THREAD

**Issue by nxygen** [seiuna/puu-uuuuuuuuuuuu#11]
如题，我将项目封装进了docker，但是如果不使用伪终端，那么无法完成启动操作

**Comment by seiuna** [comment]
![image](https://github.com/pu-client/oyasumi/assets/89861275/a162ecc0-3a8f-43a6-8eda-7589c35e1adb)
是这个吗？
