### ISSUE TITLE
似乎并不能正常扫描到非本组织的活动内容

### ISSUE THREAD

**Issue by Jiale23** [seiuna/puu-uuuuuuuuuuuu#4]
![Screenshot_2024-03-01-16-12-43-310_com microsoft emmx](https://github.com/seiuna/puu-uuuuuuuuuuuu/assets/40711772/c93374c0-0eaa-4085-944e-04d8d9f4b867)
![Screenshot_2024-03-01-16-14-59-659_com xyhui-edit](https://github.com/seiuna/puu-uuuuuuuuuuuu/assets/40711772/57de1cb8-7d75-4545-b28d-ddb037cc5448)

实际上其它学院是有能参加的活动的

**Comment by Jiale23** [comment]
![Uploading Screenshot_2024-03-01-16-14-59-659_com.xyhui-edit.jpg…]()

**Comment by seiuna** [comment]
默认不会加入报名需审核的活动。但是实际上开关这个功能的也并没有实现

**Comment by seiuna** [comment]
修改config.json 中 event.allowed 为false

**Comment by Jiale23** [comment]
好的，感谢回答，我去试试看
