### ISSUE TITLE
当过滤器不能限制浮点数作为活动分数的判定值

### ISSUE THREAD

**Issue by Jiale23** [seiuna/puu-uuuuuuuuuuuu#5]
如题，如果设置成诸如0.5这样的浮点数，那么就会扫描不到活动
![QQ截图20240302213453.png](https://s2.loli.net/2024/03/02/EhVDY9IGqgiQk2H.png)
![QQ截图20240302213430.png](https://s2.loli.net/2024/03/02/aKbqTZzxyogeU5R.png)

**Comment by seiuna** [comment]
``` typescript   
if(parseInt(e.score)<v.score){
            flag2=flag2&&false;
 }
```
犯了个低级错误

**Comment by seiuna** [comment]
我可以问一下这个活动的分数是多少吗？

**Comment by Jiale23** [comment]
> 我可以问一下这个活动的分数是多少吗？

是两分昂🤔

**Comment by seiuna** [comment]
已修复 应该
